### ISSUE TITLE
Je potrebné spísať podrobné poznámky zo stretnutia so zadávateľom!

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2022-FMFI/weight-inspection#1]
Podrobné poznámky je potrebné následne poslať zadávateľovi na kontrolu, doplnenie a prípadné opravenie.

**Comment by Tenshi2000** [comment]
Podrobné poznámky vypracoval Erik Mihálik a Dominik Šidlo. Následne poznámky prešli kontrolou ostatnými členmi tímu a boli odoslané na kontrolu, doplnenie a prípadné opravenie zadávateľovi. V prílohe dokladám aj samotný dokument s poznámkami.

[Podrobné poznámky zo stretnutia.pdf](https://github.com/TIS2022-FMFI/weight-inspection/files/9705301/Podrobne.poznamky.zo.stretnutia.pdf)

**Comment by flakeua** [comment]
Aj ja som precital, a vsetko je fajn

**Comment by warmac9** [comment]
vsetko je v poriadku
