### ISSUE TITLE
Vytvorenie návrhu používateľského rozhrania (GUI).

### ISSUE THREAD

**Issue by warmac9** [TIS2022-FMFI/weight-inspection#10]
Zadanie:
Nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom - túto časť treba konzultovať so zadávateľom.

**Comment by Tenshi2000** [comment]
Vytvoril som návrh používateľského rozhrania (GUI) pre náš Projekt. Ešte stále nie je dokončený na 100%.

Dokladám dva link-y, na ktorých je celý návrh znázornený:
https://app.moqups.com/zoHqNAj4fHKeyJPFYTMrEqPhTlv0iYHJ/view/page/ad64222d5
https://app.moqups.com/FC8dTNjRiCVEiBxh7QYtnzY7sdX01XWH/view/page/ad64222d5

**Comment by Tenshi2000** [comment]
Hotový návrh používateľského rozhrania (GUI) bol niekoľkokrát skonzultovaný s naším Klientom a rovnako s naším Cvičiacim. 
Všetky ich pripomienky som dôkladne do návrhu zapracoval a tak samotný návrh pokladám za uzavretý.

Pre úplnosť opäť dokladám hypertextové odkazy na hotový návrh používateľského rozhrania (GUI):
https://app.moqups.com/zoHqNAj4fHKeyJPFYTMrEqPhTlv0iYHJ/view/page/ad64222d5
https://app.moqups.com/FC8dTNjRiCVEiBxh7QYtnzY7sdX01XWH/view/page/ad64222d5
