### ISSUE TITLE
Vytvorenie UML state, alebo UML sequence diagramu.

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#11]
Je potrebné vytvoriť UML state, alebo UML sequence diagram. Kľudne oboje, ale minimálne jedno z toho.

**Comment by letenay7** [comment]
vytvoril som UML sequence diagram pre zamestnanca v sklade
Na tomto linku si ho mozete pozriet a pripadne upravit
https://app.diagrams.net/#G1JMqVhP-DWFDidUEyEAO-7z4pYR3gNDBD

**Comment by Tenshi2000** [comment]
Vytvoril som UML stavový diagram pre entitu "Tovar". Hotový stavový diagram bol skontrolovaný Cvičiacim.
Nakoľko Cvičiaci nemal žiadne pripomienky, tak pokladám stavový diagram za uzavretý.

Dokladám hypertextový odkaz na hotový stavový diagram:
https://app.diagrams.net/#G1Jmw6wzerrRj5q8_cbyecaEpxyiVkCIA5

**Comment by Tenshi2000** [comment]
Nakoľko je podľa zadania postačujúce keď vytvoríme iba jeden z vyššie uvedených diagramov a stavový diagram už máme, tak sme sa v rámci tímu dohodli, že pre urýchlime proces vývoja informačného systému a to tým, že sekvenčný diagram nebudeme vytvárať. 
Týmto považujem oficiálne toto Issue za uzavreté. V prípade potreby môžeme skonzultovať znovuotvorenie tohto problému.
