### ISSUE TITLE
Vytvorenie UML component diagramu.

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#13]
Je potrebné vytvoriť UML component diagram.

**Comment by flakeua** [comment]
Vytvoril som zakladnu verziu UML component diagramu

https://app.diagrams.net/#G1zW4YTl-B2LyNa-nlKb53fNRiTg_o-3fD

**Comment by flakeua** [comment]
Prerobil som front end cast diagramu, a vidim ze Dominik vytvoril este jednu stranku z back end castou. Asi je dobra idea mergnut tieto dva diagramy do jedneho uplneho diagramu pre cely system.

**Comment by warmac9** [comment]
Upravil som vzťahy medzi komponentami backend diagramu, vytvoril som vysvetlivky k jednotlivým častiam backendu a spojil som backend s frontend diagramom.

**Comment by warmac9** [comment]
Vysvetlivky k backend komponentom:

> Explanation of components
> 
> Controller
> - expose application through API
> - communicates with services to achieve its goal
> 
> Service
> - contains business logic
> - communicates with repositories in order to serve data
> 
> Repository
> - communicates with database
> - sql commands are autogenarated by Spring framework
> 
> Model
> - represents data

**Comment by flakeua** [comment]
Pridavam jednoduchy popis component diagramu pre front end:

Typy componentov:

-     Controller:
        Kazda obrazovka aplikacie ma prideleny controller. Jeho responsibilita je spracovat eventy(stlačenie tlacidla, zmena textu  atd.) a priradovat data k prvkam gui.
- 
-     State:
        Existuju dva state’s, jeden pre gui pracovnika a druhy pre gui administratora. Sluzi na prenesenie dat medzi obrazovkamy aplikacie, chranenie globalneho state aplikacie a kontrolu navigacie medzi obrazkamy.
- 
-     Repository:
        Vyuziva API na nacitanie dat a preraba tieto data do potrebnych modelovych Java tried.

Konkretne componenty:

-     AHClientHandler:
        Abstrahuje komunikaciu z serverom do jednoduchsieho interface.
- 
-     WeightReader:
        Cita valu z elektronickeho indicatora vahy Orion.
- 
-     WeighingChecker:
        Zebra data o tekucom vazeni zo state, a overuje ich cez API.
- 
-     EmailHandler:
        Dava moznost posielat email. Na posielanie vyuziva back end cez API.

**Comment by Tenshi2000** [comment]
Všetky pripomienky boli do komponentného diagramu dôkladne zapracované. Hotový komponentný diagram bol vysvetlený a 
následne skontrolovaný Cvičiacim. Nakoľko Cvičiaci nemal žiadne pripomienky, tak pokladám toto issue za uzavreté.

Dokladám hypertextový odkaz na hotový komponentný diagram (vysvetlenie je uvedené v komentároch vyššie):
https://app.diagrams.net/#G1zW4YTl-B2LyNa-nlKb53fNRiTg_o-3fD
