### ISSUE TITLE
Vysvetlenie architektúry.

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#17]
Zadanie:
Je potrebné zrozumiteľne popísať a vysvetliť celú architektúru.

Priblíženie zadania:
Najskôr je potrebné vymyslieť, ako systém rozdeliť na čo najmenej závislé (najnezávislejšie) časti. Myslí sa pod tým aj to, akým spôsobom budú komponenty komunikovať - či sa na to použijú nejaké podporné komponenty, alebo aká technológia. 
Tiež by mala byť jasná predstava, čo bude potrebné urobiť, aby sa pridal ďalší komponent.

**Comment by warmac9** [comment]
Modul, ktorý má na starosť komunikáciu s emailom by sa mal presunúť do backendu v prípade, že počítač na ktorom bude bežať aplikácia pre zamestnávateľa skladu nebude mať prístup k internetu.
Treba zvážiť, či by "business logic" ako napr. výpočet hmotnosti nebolo dobré presunúť do backendu, že by klient slúžil výhradne ako "frontend"

**Comment by letenay7** [comment]
Tvoj navrh znie rozumne. Mozeme to este vyriesit na stretnuti a pripadne zmenit niektore moduly podla potreby

**Comment by letenay7** [comment]
Vytvoril som zdielany dokument s vysvetlenim architektury systemu, ktory mozeme vsetci upravovat
https://docs.google.com/document/d/1ORaBUI71nVLGML1XOnbR2w7H2iiQqikPVxlLtYw-quM/edit?usp=sharing

Taktiez prikladam linku na diagram ktory sme s Dominikom vytvorili lebo si myslim ze by tu mal byt ale nikto ho sem este nedal
https://app.diagrams.net/#G1FdDmf56iuBpuQd9623MeEmts2of5bvY_
