### ISSUE TITLE
Vysvetlenie rozdelenia na časti (moduly) a ich interfejsy.

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#18]
Je potrebné zrozumiteľne popísať a vysvetliť rozdelenie na časti (moduly) a ich interfejsy. Jedná sa o to isté rozdelenie na moduly, ktoré sa bude nachádzať v komponentnom diagrame. Toto rozdelenie na moduly je potrebné vysvetliť a netreba zabudnúť na vysvetlenie rozhraní (interfejsov), ktoré sa budú nachádzať medzi týmito modulmi.

**Comment by flakeua** [comment]
Pridavam jednoduchy popis component diagramu pre front end:

Typy componentov:
    Controller:
        Kazda obrazovka aplikacie ma prideleny controller. Jeho responsibilita je spracovat eventy(stlačenie tlacidla, zmena textu  atd.) a priradovat data k prvkam gui.

    State:
        Existuju dva state’s, jeden pre gui pracovnika a druhy pre gui administratora. Sluzi na prenesenie dat medzi obrazovkamy aplikacie, chranenie globalneho state aplikacie a kontrolu navigacie medzi obrazkamy.

    Repository:
        Vyuziva API na nacitanie dat a preraba tieto data do potrebnych modelovych Java tried.

Konkretne componenty:
    AHClientHandler:
        Abstrahuje komunikaciu z serverom do jednoduchsieho interface.

    WeightReader:
        Cita valu z elektronickeho indicatora vahy Orion.

    WeighingChecker:
        Zebra data o tekucom vazeni zo state, a overuje ich cez API.

    EmailHandler:
        Dava moznost posielat email. Na posielanie vyuziva back end cez API.
