### ISSUE TITLE
Vysvetlenie využitých technológií.

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#19]
Je potrebné zrozumiteľne popísať a vysvetliť každú z využitých technológií.

**Comment by letenay7** [comment]
zase som vytvoril zdielany dokument na ktorom budeme pracovat a doplnat ho postupne

https://docs.google.com/document/d/1EeDcEP6LB6wEsmFPrm91qgcGoZ8qjp0kKBm03uF_wV0/edit?usp=sharing

**Comment by warmac9** [comment]
Vysvetlil som využité technológie ohľadom backendu.

**Comment by Tenshi2000** [comment]
Všetky využité technológie boli do dokumentu zaznamenané, skontrolované a pridané do dokumentu "Návrh implementácie".
Ak by sa v budúcnu vyskytli nové použité technológie, tak sa objavia dodatočne v komentári a neskôr budú pridané aj do
príslušných dokumentov kvôli dokumentácií. Pre tento moment považujem toto issue za uzavreté.
