### ISSUE TITLE
Je potrebné vytvoriť neusporiadaný, nie nutne konzistentný, úplný a jednoznačný "Zoznam požiadaviek" na základe "Podrobných poznámok zo stretnutia"!

### ISSUE THREAD

**Issue by warmac9** [TIS2022-FMFI/weight-inspection#2]
Je potrebné vytvoriť neusporiadaný, nie nutne konzistentný, úplný a jednoznačný "Zoznam požiadaviek" na základe "Podrobných poznámok zo stretnutia"! Po dokončení je potrebné dokument poslať na kontrolu nášmu klientovi a zohľadniť všetky prípadné pripomienky.

**Comment by warmac9** [comment]
Vytvoril som neusporiadany zoznam poziadavok
[Neusporiadaný, úplný a jednoznačný zoznam požiadaviek.docx.pdf](https://github.com/TIS2022-FMFI/weight-inspection/files/9791578/Neusporiadany.uplny.a.jednoznacny.zoznam.poziadaviek.docx.pdf)

**Comment by Tenshi2000** [comment]
Neusporiadaný zoznam požiadaviek vypadá byť v poriadku. Do výsledného katalógu to však bude chcieť ešte úpravu.
Každopádne dobrá práca. Ďakujem, Dominik.
