### ISSUE TITLE
Vytvorenie programu na otestovanie back end-u.

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#23]
Je potrebné vytvoriť program v programovacom jazyku Java verzie 8, ktorým otestujeme prístup k databáze (back end). 
Bude potrebné si vytvoriť novú databázu a v nej tabuľku, na ktorej sa budú následne realizovať CRUD operácie. 
Zvolená technológia (pravdepodobne): Java Spring.

**Comment by warmac9** [comment]
Úspešne som vytvoril základnu testovaciu verziu backendu v Spring frameworku, čo zahŕňalo:

- CRUD operácie nad jednou entitou
- prepojenie Spring s Postgres databázou
- základná autorizácia a autentifikácia

**Comment by Tenshi2000** [comment]
Dominik dnes (03.12.2022) na tímovom stretnutí o 11:20 odprezentoval a vysvetlil vyššie uvedený testovací program, ktorý vytvoril.
Týmto považujem oficiálne toto Issue za uzavreté - v prípade potreby môžeme skonzultovať znovuotvorenie.
