### ISSUE TITLE
Vytvorenie programu na otestovanie posielania e-mailov.

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#24]
Je potrebné vytvoriť program v programovacom jazyku Java verzie 8 (pravdepodobne za pomoci dostupných knižníc), ktorým otestujeme posielanie notifikácií pre administrátora prostredníctvom e-mailov na jeho súkromnú e-mailovú adresu.
Zároveň by bola rozumná realizácia, ktorá by podporovala / fungovala s Java Spring-om.

**Comment by letenay7** [comment]
[MailPrototype.zip](https://github.com/TIS2022-FMFI/weight-inspection/files/10090223/MailPrototype.zip)
Vytvoril som testovaci program na posielanie emailov pomocou JavaMail API. Klient nam vytvoril emailovu adresu z ktorej bude nasa aplikacia maily posielat. Testoval som to posielanim mailov na svoj sukromny aj univerzitny mail a aj klientiovi na stretnuti
Vsetko fungovalo bez problemov

**Comment by Tenshi2000** [comment]
Martin dnes (26.11.2022) na tímovom stretnutí o 10:00 odprezentoval a vysvetlil vyššie uvedený testovací program, ktorý vytvoril.
Týmto považujem oficiálne toto Issue za uzavreté - v prípade potreby môžeme skonzultovať znovuotvorenie.
