### ISSUE TITLE
Vytvorenie jednoduchšieho UI v Java FX na otestovanie front end-u.

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#25]
Je potrebné vytvoriť jednoduchý UI v programovacom jazyku Java verzie 8 (za pomoci Java FX), ktorým otestujeme front end a zistíme, aké máme možnosti pri vytváraní finálneho UI aplikácie - pôjde o načítanie údajov z API a ich následné zobrazenie v tabuľke (GUI).

**Comment by flakeua** [comment]
Prestudoval som aku verziu java je mozne vyuzivat na komercne aplikacie a pomocou tej javy a JavaFX8 som vytrvoril jednoduchu aplikaciu. Vyuzil som este GSON pre deserializaciu JSON a AsyncHTTPClient pre requesty do webu. Navrhnul som nejaku jednoduchu architekturu, ktoru som dalej pouzil na vytvorenie component diagramu nasej aplikacii.

**Comment by Tenshi2000** [comment]
Dmytro dnes (26.11.2022) na tímovom stretnutí o 10:00 odprezentoval a vysvetlil vyššie uvedený testovací program, ktorý vytvoril.
Týmto považujem oficiálne toto Issue za uzavreté - v prípade potreby môžeme skonzultovať znovuotvorenie.
