### ISSUE TITLE
Vytvorenie testovacích scenárov.

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#28]
Je potrebné vytvoriť dokument s testovacími scenármi, ktorý vznikne podľa Katalógu požiadaviek. Jeden scenár môže testovať aj viacero požiadaviek, ale každá požiadavka z katalógu musí byť kompletne pokrytá v nejakom testovacom scenári. Dokument využijete na to, aby ste skontrolovali, že všetko, čo má byť hotové je implementované a funguje. Neslúži na podrobné testovanie všetkých prípadov - na to je vhodné vytvárať jednotkové testy, ktoré sa dajú zbehnúť.

**Comment by flakeua** [comment]
Precital som dokument, a napisal som pripomienky, ako komentare do Google docu.

**Comment by letenay7** [comment]
Podla Dmytrovych pripomienok som jemne upavil dokument 
Prikladam k nemu link
https://docs.google.com/document/d/1y0GKGNlaaK-U1K1WIaGvi9EvzZkYEOoRB-t1Ip_Zp0A/edit?usp=sharing

**Comment by Tenshi2000** [comment]
Dokument som si prečítal, skontroloval, upravil a zakomponoval do nášho dokumentu s názvom "Návrh".
Týmto pokladám toto issue za uzavreté. V prípade potreby môžeme prediskutovať jeho znovuotvorenie.
