### ISSUE TITLE
Je potrebné zohľadniť pripomienky od klienta do "Podrobných poznámok zo stretnutia"!

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#3]
Dostal som od klienta nasledujúcu pripomienku na náš dokument "Podrobná poznámky zo stretnutia":
"Dokument bol v poriadku, ale ešte mi tam chýbala zmienka o zasielaní notifikácii a extraktu v určitom čase. 
 Chceli by sme, aby sa generoval extrakt na email-ové adresy a to nasledovne:  Každú hodinu, ak prebehlo v tom čase nové váženie. 
 Ak prebehlo nové váženie o 14:10 bude toto váženie zahrnuté v reporte o 15:00, ktorý bude zobrazovať údaje z váženia v čase od 
 14:00 do 15:00. Zároveň,  ak nebol žiadny záznam od 15:00 do 16:00, tak nebude extrakt zaslaný o 16:00."

Je potrebné dôkladne zohľadniť vyššie uvedenú pripomienku do nášho dokumentu "Podrobná poznámky zo stretnutia".
Následne už iba aktualizovaný dokument nahrať z dôvodu dokumentácie.

**Comment by Tenshi2000** [comment]
Pripomienky od klienta som dôkladne zohľadnil. Následne si aktualizovaný dokument prečítali ostatní členovia tímu a bol odoslaný na kontrolu, doplnenie, a prípadné opravenie zadávateľovi. V prílohe dokladám aj samotný aktualizovaný dokument.

[Podrobné poznámky zo stretnutia.pdf](https://github.com/TIS2022-FMFI/weight-inspection/files/9725613/Podrobne.poznamky.zo.stretnutia.pdf)

**Comment by letenay7** [comment]
myslím si že by s tým nemal byť problém.

**Comment by warmac9** [comment]
z mojej strany, všetko je v poriadku

**Comment by flakeua** [comment]
Vsetko je fajn
