### ISSUE TITLE
Je potrebné vytvoriť "Výsledný katalóg požiadaviek"!

### ISSUE THREAD

**Issue by warmac9** [TIS2022-FMFI/weight-inspection#4]
Vytvoriť katalóg požiadaviek, ktorý odsúhlasil zadávateľ (na piatkovom online stretnutí). Kým mal zadávateľ pripomienky, treba ich najskôr zohľadniť a ponúknuť mu na odsúhlasenie aktualizovanú, vylepšenú verziu. Pred tým, ako sa posiela návrh katalógu požiadaviek zadávateľovi, ho musí schváliť cvičiaci.

**Comment by letenay7** [comment]
Na katalogu sa uz aktivne pracuje vo forme google docu
https://docs.google.com/document/d/12_l8GeEfJTpNSyC1ckYvAe5DSSS5mEQz-vN04VtvD2c/edit
Postupne do neho piseme jednotlive kapitoly ale asi to este par dni potrva

**Comment by Tenshi2000** [comment]
Dokončil som posledné úpravy na našom katalógu požiadaviek. Zohľadnil som všetky pripomienky kladené na dokument.
Zároveň som kontaktoval cvičiaceho a poprosil ho o kontrolu nášho dokumentu. Ak bude všetko vyhovovať, tak odošlem 
dokument klientovi. Naopak pri zistení prípadných nedostatkov sa postarám o ich elimináciu.

**Comment by letenay7** [comment]
dokument som vcera kontroloval a vidim ze si zapracoval moje pripomienky takze mozeme to poslat cviciacemu

**Comment by flakeua** [comment]
Precital/skontroloval som dokument, a vsetko vyzera dobre.

**Comment by Tenshi2000** [comment]
Poslal som dokument na kontrolu cvičiacemu a zohľadnil všetky pripomienky. Následne som dokument poslal na kontrolu klientovi a rovnako zohľadnil všetky pripomienky. Dokument týmto považujem oficiálne za hotový a uzavretý. 

Dokladám finálnu verziu dokumentu "Katalóg Požiadaviek":
[Katalóg Požiadaviek.pdf](https://github.com/TIS2022-FMFI/weight-inspection/files/9889296/Katalog.Poziadaviek.pdf)

**Comment by Tenshi2000** [comment]
V dokumente boli vykonané menšie zmeny na základe odporúčaní od pána Cvičiaceho a na základe pripomienok od klienta. 
Zároveň som opravil zopár gramatických a štylistických chýb, ktoré sa v dokumente nachádzali.

Dokladám aktualizovanú finálnu verziu dokumentu "Katalóg požiadaviek":
[Katalóg Požiadaviek.pdf](https://github.com/TIS2022-FMFI/weight-inspection/files/9912930/Katalog.Poziadaviek.pdf)
