### ISSUE TITLE
Je potrebné aktualizovať "Podrobné poznámky zo stretnutia"!

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#5]
Je potrebné dôkladne zohľadniť nové informácie a zmeny z posledného (online) stretnutia s klientom, ktoré sa konalo 07.10.2022 medzi 9:00 - 11:00 do "Podrobných poznámok zo stretnutia". Všetky informácie zo stretnutia sú zaznamenané v nahrávke, ktorú by nám mal už v najbližšom čase poskytnúť náš klient. Po aktualizovaní dokumentu ho sem nahrajte z dôvodu dokumentácie.

**Comment by Tenshi2000** [comment]
Po dodaní nahrávky zo stretnutia s klientom (z dňa 07.10.2022) som na základe získaných informácií (z nahrávky) aktualizoval dokument "Podrobné poznámky zo stretnutia" a obohatil ho o niekoľko otázok pre klienta. Dokument som poslal klientovi. 
Pripomienky od klienta som dôkladne zohľadnil. V prílohe dokladám dve verzie dokumentu z dôvodu dokumentácie.

Dokument vo verzii 3.0 (už aktualizovaný dokument s otázkami na klienta):
[Podrobné poznámky zo stretnutia (verzia 3.0).pdf](https://github.com/TIS2022-FMFI/weight-inspection/files/9767351/Podrobne.poznamky.zo.stretnutia.verzia.3.0.pdf)
Dokument vo verzii 4.0 (dokument po zohľadnení pripomienok od klienta):
[Podrobné poznámky zo stretnutia (verzia 4.0).pdf](https://github.com/TIS2022-FMFI/weight-inspection/files/9767354/Podrobne.poznamky.zo.stretnutia.verzia.4.0.pdf)

**Comment by letenay7** [comment]
Erik poznamky aktualizoval a ja s nimi suhlasim

**Comment by flakeua** [comment]
Vsetko je fajn
