### ISSUE TITLE
Je potrebné vytvoriť základnú štruktúru "Výsledného katalógu požiadaviek"!

### ISSUE THREAD

**Issue by Tenshi2000** [TIS2022-FMFI/weight-inspection#6]
Je potrebné vytvoriť základnú štruktúru "Výsledného katalógu požiadaviek"! 
Ide o dokument, ktorý bude obsahovať iba základnú kostru (bez obsahu).

**Comment by letenay7** [comment]
Vytvoril som pre tento účel zdielaný google document aby sme to mohli upravovať
Štruktúra tam už je, pribudne este dnes nejaký basic obsah
Tu je link"
https://docs.google.com/document/d/12_l8GeEfJTpNSyC1ckYvAe5DSSS5mEQz-vN04VtvD2c/edit?usp=sharing
poslite pripadne pripomieky

**Comment by Tenshi2000** [comment]
V štruktúre som urobil menšie zmeny: upravil veľkosť, zmenil hrúbku a trošku štylizáciu niekedy. 
Inak to bolo všetko funkčné a myslím si, že katalóg potrebuje už iba obsah. Ďakujem, Martin.

**Comment by flakeua** [comment]
Struktura je dobra.
