### ISSUE TITLE
Vytvorenie podrobného dátového modelu perzistentných údajov.

### ISSUE THREAD

**Issue by warmac9** [TIS2022-FMFI/weight-inspection#9]
Zadanie:
Podrobný dátový model perzistentných údajov (napr. pgadmin, formátov súborov, komunikačných protokolov, ...).

Poznámky:
- Očakávané stĺpce zadané klientom sú uložené na Ms Teams-e.

**Comment by pavelpetrovic** [comment]
* navrhujem cesty k obrazkom evidovat priamo v tabulkach obal, paleta
* v merani chyba datum/cas a ze ci bolo uz exportovane

**Comment by Tenshi2000** [comment]
Pripomienky k dátového modelu perzistentných údajov:
- Navrhujem celý model preložiť do anglického jazyka.
- Musíme: Celý model skontrolovať s poznámkami a katalógom požiadaviek.
- Musíme: Minimálne ku každej tabuľke uviesť aspoň 1-2 vety na vysvetlenie.
- Nemusíme, ale môžeme: 1-2 vety by sa mohli uviesť aj ku každému stĺpcu tabuľky.

Ps: 1-2 vety popisu by sa však dali alternatívne napísať aj v rámci komentáru 
(napr. v MySQL je taká možnosť priamo pri vytváraní štruktúry).

**Comment by flakeua** [comment]
Zapracoval som všetky pripomienky napísane vyššie, ešte existujú nejaké otázky, ktoré môžu tento model trosku zmeniť, ale je už tato verzia blízka ku finálnej.

**Comment by warmac9** [comment]
Treba doriešiť ešte otázku "tolerancie", aby sme ju vedeli správne zapracovať do modelu. Takže čakáme na odpoveď od klienta na otázku: "Podľa akých parametrov vieme nastaviť toleranciu".

**Comment by Tenshi2000** [comment]
Dnes (31.10.2022) sa konalo stretnutie s klientom, na ktorom sme získali všetky potrebné informácie.
Zaznamenal som ich do dokumentu "Podrobné poznámky zo stretnutia (verzia 9.0)". Poprosím vás o 
ich zapracovanie do nášho podrobného dátového modelu perzistentných údajov. Ďakujem.

**Comment by warmac9** [comment]
Zhrnutie poznámok od klienta, ktoré treba zakomponovať do databázy:

Tolerancia nemôže byť väčšia ako váha jedného kusu, pretože by mohol jeden kus chýbať, preto sa tolerancia bude zapisovať ako percento z jedného kusu.

Klient požadoval, aby sa váha dala nastaviť aj podľa obalu aj referencie, preto by bolo toleranciu dobre presunúť do tabuľky "packaging_product"

**Comment by Tenshi2000** [comment]
Zhrnutie zmien, ktoré je potrebné vykonať na našom "Podrobnom dátovom modely perzistentných údajov":

1. V tabuľke "Admins" je potrebné o každom administrátorovi viesť nasledujúce informácie: 
meno, priezvisko, prihlasovacie meno, prihlasovacie heslo.
2. Je potrebné upraviť, kde sa má nachádzať tolerancia v modely (viď. Dominikov komentár vyššie).
3. Je potrebné skontrolovať, či vyhovuje riešenie obrázkov (umiestnenie v modely).

PS: Bližšie (detailnejšie) informácie o každom z vyššie uvedených bodov nájdete v dokumente 
"Katalóg požiadaviek",  alebo v dokumente "Podrobné poznámky zo stretnutia (verzia 9.0)".

**Comment by flakeua** [comment]
https://app.quickdatabasediagrams.com/#/d/MmyeLQ
Zapracoval som vsetky pripomienky a presuvam ten model do In Review

**Comment by Tenshi2000** [comment]
Je nutné do dátového modelu zahrnúť nasledujúce pripomienky:
1. Pridať novú tabuľku pre notifikácie systému (administrátora).
2. Pridať novú tabuľku pre e-mailové adresy.
3. Pridať vzťah medzi tabuľkou administrátorov a tabuľkou e-mailov (cez ID e-mailov).

**Comment by Tenshi2000** [comment]
Všetky pripomienky boli do dátového modelu dôkladne zapracované. Hotový dátový model bol skontrolovaný Cvičiacim.
Nakoľko Cvičiaci nemal žiadne pripomienky, tak pokladám dátový model perzistentných údajov za uzavretý.

Dokladám hypertextový odkaz na hotový dátový model perzistentných údajov:
https://app.quickdatabasediagrams.com/#/d/MmyeLQ
